export const org: string;
export const center: string;
export const projGroup: string;
export const projItem: string;
export const projInfo: string;
export const action: string;
export const projIcon: string;
export const iconEdit: string;
export const iconStar: string;
